service: github-actions-badge

# Load custom settings
custom: ${file(./settings.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ${self:custom.region}
  accessToken: ${self:custom.accessToken}

package:
  exclude:
    - coverage/
    - server.js
    - test/

functions:
  badge:
    handler: handler.handle
    environment:
      GITHUB_ACCESS_TOKEN: ${self:provider.accessToken}
    events:
      - http:
          path: badge/{owner}/{repo}/{isPrivate}
          method: get
